#!/bin/expect
set ip [lindex $argv 0 ]  
set port [lindex $argv 1]
set passwd [lindex $argv 2 ] 
set timeout 10
spawn ssh $ip -p $port
expect {  
 	"*yes/no" { send "yes\r"; exp_continue}  
 	"*assword:" { send "$passwd\r" }  
}  
expect "*@*"    
# 重设 session 的 LC_CTYPE，否则会出现乱码
send "export LC_CTYPE=\${LANG}\r clear\r"
trap {
 set rows [stty rows]
 set cols [stty columns]
 stty rows $rows columns $cols < $spawn_out(slave,name)
} WINCH
interact